### ISSUE TITLE
Ocicats Review

### ISSUE THREAD

**Issue by santiagorodriguezbermudez** [umairarshadbutt/Enumerable-Methods#2]
### Kudos on the following:
- Nice to work on getting this project accepted. 

### Please work on the following:
- [x] Naming convention on some variables could be improved. Instead of the index, should be an element. 
- [x] Next time, don't disable Rubocop restrictions. Rubocop forces you write better quality code. 
- [ ] Refactor injects method to make it simpler. It is too complex.

**Comment by umairarshadbutt** [comment]
Thanks @santiagorodriguezbermudez
